apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod-visitor
  name: test-pod-visitor
spec:
  initContainers:
  - name: init-busybox
    image: busybox:1.28
    command: ['sh', '-c', "echo Init"]
  containers:
  - image: nginx
    name: nginx
  - image: ubuntu
    name: ubuntu
    command: ['sh', '-c', "sleep infinity"]
