openapi: 3.1.0
info:
  title: Exsample API
  description: サンプル API
  version: 1.0.0
  contact:
    name: Exsample Developent
    email: [email protected]
servers:
  - url: 'http://localhost:88'
    description: 開発環境
paths:
  '/api/v1/users/{user_id}':
    get:
      description: ユーザ詳細
      operationId: UserShow
      parameters:
        - $ref: '#/components/parameters/PathUserId'
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      description: ユーザ更新
      operationId: UserUpdate
      parameters:
        - $ref: '#/components/parameters/PathUserId'
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  '/api/v1/users':                               # POSTを追加でもシンプルに書けます
    post:
      description: ユーザ作成
      operationId: UserCreate
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  parameters:
    PathUserId:
      name: user_id
      in: path
      required: true
      schema:
        type: integer
      description: ユーザID
  requestBodies:
    User:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              age:
                type: integer
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time